apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: odoo-enterprise
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/instance: odoo
    app.kubernetes.io/component: enterprise-image
spec:
  lookupPolicy:
    local: true
