apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/instance: odoo
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
