apiVersion: v1
kind: Secret
metadata:
  name: odoo
  labels:
    app.kubernetes.io/name: odoo
    app.kubernetes.io/instance: odoo
    app.kubernetes.io/component: server
type: Opaque
stringData:
  odoo-password: changeme
